export const orderHeadings = ['ORDERID', 'DISH', 'PRICE', 'LOCATION', 'USERID', 'ACTIONS'];
export const orderItems = [
		{
			orderid: '123',
			dish: '2 Veg Burgers',
			price: 'Rs.350',
			location: 'Noida',
			userid: '321',
			isNumeric: true,
		},
		{
			orderid: '124',
			dish: '1 Masala Dosa',
			price: 'Rs.150',
			location: 'Delhi',
			userid: '322',
		},
		{
			orderid: '125',
			dish: '1 veg Noodles',
			price: 'Rs.250',
			location: 'Noida',
			userid: '321',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},

		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
		
		{
			orderid: '126',
			dish: '2 plate Chicken Momos',
			price: 'Rs.350',
			location: 'Delhi',
			userid: '432',
		},
	];
